### ISSUE TITLE
⚖️ Register Validator:  MELLIFERA

### ISSUE THREAD

**Issue by RuslanGlaznyov** [axone-protocol/networks#795]
### Network Choice

dentrite-1

### Who are you?

As a small team our main focus to a small number of projects that will bring big value to the web3 world. With this approach, we can make unique contributions which required by specific projects (explorers, monitoring tools, web apps). Our developer experience in web3 can be found on our GitHub. [https://github.com/mellifera-labs](https://github.com/mellifera-labs)

Also, we had experience providing infrastructure such as IBC, RPCs, restapis, snapshots, state sync. 

Community  builder in [namada](https://github.com/anoma/namada) and developer and spec champion in [Lava network](https://github.com/lavanet/lava)  

### Delegator address

axone1cvclz3u9zrpfvrhymds9pjp63x94wcujv95zxf

### gentx

```json
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"MELLIFERA","identity":"8F3D842B29B89CC5","website":"https://mellifera.network","security_contact":"team@mellifera.network","details":"Empowering blockchain security and contributing to cosmos ecosystem with technical expertise"},"commission":{"rate":"0.050000000000000000","max_rate":"0.200000000000000000","max_change_rate":"0.010000000000000000"},"min_self_delegation":"1","delegator_address":"","validator_address":"axonevaloper1cvclz3u9zrpfvrhymds9pjp63x94wcujuscsut","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"kQCXF8CQHpypKL1guZpCneDerETIbERkUMLAVcFZOoE="},"value":{"denom":"uaxone","amount":"1000000000000"}}],"memo":"f30b33834ddcb95051ab4d0fed9ae85c09b44a44@65.108.100.31:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A2th+gbEJJNf/gbCXyWDCBxYZ5k2nYoi1n8YvQS9BftU"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""},"tip":null},"signatures":["4ucgiB13u6fSg1LPTfR4pFWe2T1dIfNsCQQqpx7bInV1fduYNwDnPtV7/uJ4iReSpbAyjZCjJhX74l6ftCAzbQ=="]}
```

**Comment by amimart** [comment]
Done 😉 https://github.com/axone-protocol/networks/pull/796
